var res = {
    HelloWorld_png : "res/HelloWorld.png",
    back_btn_png: "res/niuniu/back-btn.png",
    banner_png: "res/niuniu/banner.png",
    bank_title_png: "res/niuniu/bank-title.png",
    bet_amount_token_png: "res/niuniu/bet-amount-token.png",
    bet_amount_total_png: "res/niuniu/bet-amount-total.png",
    blackjack_jpg: "res/niuniu/blackjack.jpg",
    btn_wrap_png: "res/niuniu/btn-wrap.png",
    cancel_icon_png: "res/niuniu/cancel-icon.png",
    clock_png: "res/niuniu/clock.png",
    coin_sprite_50_png: "res/niuniu/coin-sprite-50.png",
    coin_sprite_100_png: "res/niuniu/coin-sprite-100.png",
    coin_sprite_500_png: "res/niuniu/coin-sprite-500.png",
    coin_sprite_1000_png: "res/niuniu/coin-sprite-1000.png",
    coin_sprite_5000_png: "res/niuniu/coin-sprite-5000.png",
    coin_sprite_10000_png: "res/niuniu/coin-sprite-10000.png",
    coin_sprite_custom_png: "res/niuniu/coin-sprite-custom.png", 
    coin_wrap_png: "res/niuniu/coin-wrap.png",
    confirm_icon_png: "res/niuniu/confirm-icon.png",
    help_btn_png: "res/niuniu/help-btn.png",
    sound_on_btn_png: "res/niuniu/sound-on-btn.png",
    sound_off_btn_png: "res/niuniu/sound-off-btn.png",
    table_img_png: "res/niuniu/table_img.png",
    serial1_png: "res/niuniu/serial1.png",
    serial2_png: "res/niuniu/serial2.png",
    serial3_png: "res/niuniu/serial3.png",
    serial4_png: "res/niuniu/serial4.png",
    serial5_png: "res/niuniu/serial5.png",
    serial6_png: "res/niuniu/serial6.png",
    serial7_png: "res/niuniu/serial7.png",
    serial8_png: "res/niuniu/serial8.png",
    serial9_png: "res/niuniu/serial9.png",
    serial10_png: "res/niuniu/serial10.png",
    history_active_btn: "res/niuniu/history_active_btn.png",
    history_nonactive_btn: "res/niuniu/history_nonactive_btn.png",
    history_blue_circle: "res/niuniu/history_blue_circle.png",
    green_btn_png: "res/niuniu/green-btn.png",
    red_btn_png: "res/niuniu/red-btn.png",
    check_radio_png: "res/niuniu/check-radio.png",
    dlg_no_btn_png: "res/niuniu/dlg-no-btn.png",
    dlg_yes_btn_png: "res/niuniu/dlg-yes-btn.png",
    card_sheet_png: "res/niuniu/cards/cardSheet.png",
    card_sheet_plist: "res/niuniu/cards/cardSheet.plist",
    card1c: "res/niuniu/cards/card1C.png",
    card1d: "res/niuniu/cards/card1D.png",
    card1h: "res/niuniu/cards/card1H.png",
    card1s: "res/niuniu/cards/card1S.png",
    card2c: "res/niuniu/cards/card2C.png",
    card2d: "res/niuniu/cards/card2D.png",
    card2h: "res/niuniu/cards/card2H.png",
    card2s: "res/niuniu/cards/card2S.png",
    card3c: "res/niuniu/cards/card3C.png",
    card3d: "res/niuniu/cards/card3D.png",
    card3h: "res/niuniu/cards/card3H.png",
    card3s: "res/niuniu/cards/card3S.png",
    card4c: "res/niuniu/cards/card4C.png",
    card4d: "res/niuniu/cards/card4D.png",
    card4h: "res/niuniu/cards/card4H.png",
    card4s: "res/niuniu/cards/card4S.png",
    card5c: "res/niuniu/cards/card5C.png",
    card5d: "res/niuniu/cards/card5D.png",
    card5h: "res/niuniu/cards/card5H.png",
    card5s: "res/niuniu/cards/card5S.png",
    card6c: "res/niuniu/cards/card6C.png",
    card6d: "res/niuniu/cards/card6D.png",
    card6h: "res/niuniu/cards/card6H.png",
    card6s: "res/niuniu/cards/card6S.png",
    card7c: "res/niuniu/cards/card7C.png",
    card7d: "res/niuniu/cards/card7D.png",
    card7h: "res/niuniu/cards/card7H.png",
    card7s: "res/niuniu/cards/card7S.png",
    card8c: "res/niuniu/cards/card8C.png",
    card8d: "res/niuniu/cards/card8D.png",
    card8h: "res/niuniu/cards/card8H.png",
    card8s: "res/niuniu/cards/card8S.png",
    card9c: "res/niuniu/cards/card9C.png",
    card9d: "res/niuniu/cards/card9D.png",
    card9h: "res/niuniu/cards/card9H.png",
    card9s: "res/niuniu/cards/card9S.png",
    card10c: "res/niuniu/cards/card10C.png",
    card10d: "res/niuniu/cards/card10D.png",
    card10h: "res/niuniu/cards/card10H.png",
    card10s: "res/niuniu/cards/card10S.png",
    card11c: "res/niuniu/cards/card11C.png",
    card11d: "res/niuniu/cards/card11D.png",
    card11h: "res/niuniu/cards/card11H.png",
    card11s: "res/niuniu/cards/card11S.png",
    card12c: "res/niuniu/cards/card12C.png",
    card12d: "res/niuniu/cards/card12D.png",
    card12h: "res/niuniu/cards/card12H.png",
    card12s: "res/niuniu/cards/card12S.png",
    card13c: "res/niuniu/cards/card13C.png",
    card13d: "res/niuniu/cards/card13D.png",
    card13h: "res/niuniu/cards/card13H.png",
    card13s: "res/niuniu/cards/card13S.png",

    gameBgSound_mp3: "res/niuniu/sounds/bg-sound.mp3",
    choose_coin_wav: "res/niuniu/sounds/choose-coin.wav",
    coin_drop_wav: "res/niuniu/sounds/coin-drop.wav"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}

